# --- WEBSITE 1 CONFIGURATION ---
server {
    listen 80;
    server_name web1.local localhost;

    location / {
        proxy_pass http://web1_service:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# --- WEBSITE 2 CONFIGURATION ---
server {
    listen 80;
    server_name web2.local;

    location / {
        proxy_pass http://web2_service:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
