# WEBSITE 1: Trang Web chính & Gọi API Node-RED
server {
    listen 80;
    server_name site1.hoangvu057.id.vn web.hoangvu057.id.vn localhost;

    location / {
        root /usr/share/nginx/html1;
        index index.html;
    }

    # Reverse Proxy cho API Node-RED
    location /api/ {
        proxy_pass http://nodered:1880/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

# WEBSITE 2: Trang Web thứ hai
server {
    listen 80;
    server_name site2.hoangvu057.id.vn;

    location / {
        root /usr/share/nginx/html2;
        index index.html;
    }

    # Proxy sang phpMyAdmin nếu muốn truy cập phpMyAdmin qua Nginx
    location /pma/ {
        proxy_pass http://phpmyadmin:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
